name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shake: ^2.2.0
  http: ^0.13.3
  translator: ^0.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true
  assets:
      - images/planet.png
      - images/planetRed.png
      - images/dark.png
      - images/light.png
      - images/lightRed.png
      - images/planetLight.png



